apiVersion: networking.istio.io/v1beta1
kind: WorkloadGroup
metadata:
  name: ratings
  namespace: default
spec:
  metadata:
    labels:
      app: ratings
  template:
    serviceAccount: bookinfo-ratings
